/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:598943:
  appc.background(230);
} //_CODE_:window1:598943:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:window2:248494:
  appc.background(230);
} //_CODE_:window2:248494:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("STATUS BAR");
  panelstatus = new GPanel(this, 10, 50, 180, 700, "_________.:: STATUS ::._______");
  panelstatus.setCollapsible(false);
  panelstatus.setText("_________.:: STATUS ::._______");
  panelstatus.setLocalColorScheme(GCScheme.RED_SCHEME);
  panelstatus.setOpaque(true);
  GPS = new GLabel(this, 11, 145, 50, 20);
  GPS.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  GPS.setText("GPS");
  GPS.setTextBold();
  GPS.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  GPS.setOpaque(false);
  EDF = new GLabel(this, 11, 220, 50, 20);
  EDF.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  EDF.setText("EDF");
  EDF.setTextBold();
  EDF.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  EDF.setOpaque(false);
  IMU = new GLabel(this, 11, 70, 50, 20);
  IMU.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  IMU.setText("IMU");
  IMU.setTextBold();
  IMU.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  IMU.setOpaque(false);
  sketchPad1 = new GSketchPad(this, 50, 50, 800, 800);
  panelstatus.addControl(GPS);
  panelstatus.addControl(EDF);
  panelstatus.addControl(IMU);
  panelstatus.addControl(sketchPad1);
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.addDrawHandler(this, "win_draw1");
  window2 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window2.noLoop();
  window2.addDrawHandler(this, "win_draw2");
  window1.loop();
  window2.loop();
}

// Variable declarations 
// autogenerated do not edit
GPanel panelstatus; 
GLabel GPS; 
GLabel EDF; 
GLabel IMU; 
GSketchPad sketchPad1; 
GWindow window1;
GWindow window2;
